[project]
name = "kernelpatch"
version = "1.1.6"
description = ""
authors = [
    {name = "Merculous",email = "24739823+Merculous@users.noreply.github.com"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "armfind @ git+https://github.com/merculous/pyarmfind.git"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
